#3.Creating a 2D array and perform sorting and splitting in terms of rows wise and column wise
import numpy as np
arr1 = np.array([[22,24,23],[27,26,28],[29,31,30]])
print("column =")
print()
newar = np.array_split(arr1,[1,2],axis=1)
newarr1 = np.hsplit(arr1,[1,2])
c=np.sort(arr1,axis=0)
print(newarr1)
print()
print()
print(newar)
print()
print()
print(c)
print()
print()
print("Row=")
print()
nearr=np.array_split(arr1,[1,2],axis=0)
n=np.split(arr1,[1,2],axis=0)
j=np.sort(arr1,axis=1)
print(nearr)
print()
print()
print(n)
print()
print()
print(j)